/**
 * @param {import('knex').Knex} knex
 * @returns {Promise<void>}
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('properties').del();
  
  // Insert seed entries
  await knex('properties').insert([
    {
      id: '11111111-1111-1111-1111-111111111111',
      title: 'Modern Downtown Apartment',
      description: 'Luxurious apartment in the heart of downtown with stunning city views and modern amenities.',
      price: 450000,
      property_type: 'APARTMENT',
      bedrooms: 2,
      bathrooms: 2,
      square_feet: 1200,
      lot_size: 0,
      year_built: 2018,
      status: 'ACTIVE',
      address: '123 Main Street, Apt 5B',
      city: 'New York',
      state: 'NY',
      postal_code: '10001',
      country: 'USA',
      latitude: 40.7128,
      longitude: -74.0060,
      has_garage: false,
      has_pool: true,
      has_basement: false,
      has_fireplace: false,
      parking_spaces: 1,
      heating_type: 'CENTRAL',
      cooling_type: 'CENTRAL',
      image_urls: JSON.stringify(['/uploads/properties/apartment1.jpg', '/uploads/properties/apartment2.jpg']),
      video_url: 'https://example.com/video1.mp4',
      floor_plans: JSON.stringify(['/uploads/properties/floorplan1.jpg']),
      agent_id: 'a1111111-1111-1111-1111-111111111111',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: '22222222-2222-2222-2222-222222222222',
      title: 'Suburban Family Home',
      description: 'Spacious family home in a quiet suburban neighborhood with a large backyard and modern kitchen.',
      price: 750000,
      property_type: 'HOUSE',
      bedrooms: 4,
      bathrooms: 3,
      square_feet: 2800,
      lot_size: 8000,
      year_built: 2010,
      status: 'ACTIVE',
      address: '456 Oak Avenue',
      city: 'Chicago',
      state: 'IL',
      postal_code: '60007',
      country: 'USA',
      latitude: 41.8781,
      longitude: -87.6298,
      has_garage: true,
      has_pool: false,
      has_basement: true,
      has_fireplace: true,
      parking_spaces: 2,
      heating_type: 'FORCED_AIR',
      cooling_type: 'CENTRAL',
      image_urls: JSON.stringify(['/uploads/properties/house1.jpg', '/uploads/properties/house2.jpg']),
      video_url: 'https://example.com/video2.mp4',
      floor_plans: JSON.stringify(['/uploads/properties/floorplan2.jpg']),
      agent_id: 'a2222222-2222-2222-2222-222222222222',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: '33333333-3333-3333-3333-333333333333',
      title: 'Beachfront Condo',
      description: 'Beautiful beachfront condo with panoramic ocean views and direct beach access.',
      price: 950000,
      property_type: 'CONDO',
      bedrooms: 3,
      bathrooms: 2,
      square_feet: 1800,
      lot_size: 0,
      year_built: 2015,
      status: 'ACTIVE',
      address: '789 Ocean Drive, Unit 12',
      city: 'Miami',
      state: 'FL',
      postal_code: '33139',
      country: 'USA',
      latitude: 25.7617,
      longitude: -80.1918,
      has_garage: true,
      has_pool: true,
      has_basement: false,
      has_fireplace: false,
      parking_spaces: 2,
      heating_type: 'HEAT_PUMP',
      cooling_type: 'CENTRAL',
      image_urls: JSON.stringify(['/uploads/properties/condo1.jpg', '/uploads/properties/condo2.jpg']),
      video_url: 'https://example.com/video3.mp4',
      floor_plans: JSON.stringify(['/uploads/properties/floorplan3.jpg']),
      agent_id: 'a3333333-3333-3333-3333-333333333333',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: '44444444-4444-4444-4444-444444444444',
      title: 'Mountain Cabin Retreat',
      description: 'Cozy mountain cabin with stunning views, perfect for a weekend getaway or vacation home.',
      price: 350000,
      property_type: 'CABIN',
      bedrooms: 2,
      bathrooms: 1,
      square_feet: 1200,
      lot_size: 12000,
      year_built: 1995,
      status: 'ACTIVE',
      address: '101 Pine Trail',
      city: 'Aspen',
      state: 'CO',
      postal_code: '81611',
      country: 'USA',
      latitude: 39.1911,
      longitude: -106.8175,
      has_garage: false,
      has_pool: false,
      has_basement: false,
      has_fireplace: true,
      parking_spaces: 2,
      heating_type: 'WOOD',
      cooling_type: 'NONE',
      image_urls: JSON.stringify(['/uploads/properties/cabin1.jpg', '/uploads/properties/cabin2.jpg']),
      video_url: 'https://example.com/video4.mp4',
      floor_plans: JSON.stringify(['/uploads/properties/floorplan4.jpg']),
      agent_id: 'a4444444-4444-4444-4444-444444444444',
      created_at: new Date(),
      updated_at: new Date()
    }
  ]);
};